export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 pb-14 pt-8 sm:px-6">
      <h1 className="text-4xl font-black text-white">Terms</h1>
      <div className="glass mt-8 space-y-6 rounded-2xl p-5 text-sm leading-7 text-slate-300 sm:p-7">
        <p>
          BlinkMail is provided for receiving temporary or anonymous email. You are responsible for how you use the
          addresses generated by the service.
        </p>
        <p>
          You may not use BlinkMail for spam, harassment, fraud, credential theft, malware distribution, evading lawful
          enforcement, or activity that harms others.
        </p>
        <p>
          Mail delivery depends on DNS, inbound provider routing, provider availability, and webhook configuration.
          BlinkMail does not guarantee delivery, retention, or availability of any message.
        </p>
        <p>
          We may restrict traffic, block mailboxes, remove messages, or preserve records when needed to protect the
          service or respond to abuse.
        </p>
      </div>
    </main>
  );
}

